# Generated by Django 5.1.1 on 2024-12-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
