# Generated by Django 5.1.1 on 2024-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_user_options_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
