# Generated by Django 5.1.4 on 2025-01-13 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_created_at_alter_user_update_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utulisateur"},
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="Date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("member", "Membre"), ("organisateur", "Organisateur")],
                default="membre",
                max_length=255,
                null=True,
            ),
        ),
    ]
