# Generated by Django 5.1.4 on 2025-01-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("membre", "Membre"), ("organisateur", "Organisateur")],
                default="membre",
                max_length=255,
                null=True,
            ),
        ),
    ]
