# Generated by Django 5.1.7 on 2025-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_date_joined_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="activation_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
