# Generated by Django 5.1.7 on 2025-07-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_activation_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("membre", "Membre"),
                    ("organisateur", "Organisateur"),
                    ("scanner", "Scanner"),
                ],
                default="membre",
                max_length=255,
                null=True,
            ),
        ),
    ]
