# Generated by Django 5.1.4 on 2025-02-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0001_initial"),
        ("event", "0018_rename_update_at_event_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_demande",
                to="event.infoticket",
            ),
        ),
    ]
