# Generated by Django 5.1.4 on 2025-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0002_demande_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="accronyme",
            field=models.CharField(default="event", max_length=20),
            preserve_default=False,
        ),
    ]
