# Generated by Django 5.1.4 on 2025-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0003_service_accronyme"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
