# Generated by Django 5.1.4 on 2025-02-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0004_demande_is_accepted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicehotesse",
            old_name="end_date",
            new_name="end_date_service",
        ),
        migrations.RenameField(
            model_name="servicehotesse",
            old_name="start_date",
            new_name="start_date_service",
        ),
    ]
