# Generated by Django 5.1.7 on 2025-04-04 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0006_alter_demande_anonymous_user_alter_demande_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="demande",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
