# Generated by Django 5.1.7 on 2025-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0007_demande_created_at_demande_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demande",
            name="is_accepted",
        ),
        migrations.AddField(
            model_name="demande",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Rejetée"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Statut de la demande",
            ),
        ),
    ]
