# Generated by Django 5.1.7 on 2025-05-09 16:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0008_remove_demande_is_accepted_demande_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="servicehotesse",
            name="besoin",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
