# Generated by Django 5.1.7 on 2025-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande", "0009_alter_service_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="servicehotesse",
            name="besoin",
            field=models.TextField(),
        ),
    ]
