services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=proevent
      - RABBITMQ_DEFAULT_PASS=proevent

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

