services:
  web:
    image: devibrahima/proevent:latest
    env_file: .env
    restart: always
    user: app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 2 --threads 2 --timeout 120
    ports:
      - "8080:8080"
    volumes:
      - django_static:/app/staticfiles/
    networks:
      - backend
      - traefik-public
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: "0.5"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.rule=Host(`proeventgn.com`)
      - traefik.http.routers.web-http.entrypoints=http
      - traefik.http.routers.web-http.middlewares=https-redirect
      - traefik.http.routers.web-https.rule=Host(`proeventgn.com`)
      - traefik.http.routers.web-https.entrypoints=https
      - traefik.http.routers.web-https.tls=true
      - traefik.http.routers.web-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.web.loadbalancer.server.port=8080
      - traefik.http.services.web.loadbalancer.passHostHeader=true

networks:
  backend:
  traefik-public:
    external: true

volumes:
  django_static:
