# Generated by Django 5.1.1 on 2024-12-26 17:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="partner_logo/")),
                ("description", models.TextField()),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("exclusive", "Exclusive"),
                            ("sponsor", "Sponsor"),
                            ("collaborator", "Collaborator"),
                        ],
                        default="collaborator",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference_payement", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_ticket", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("email_reception", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone_payement", models.CharField(max_length=20)),
                ("telephone_reception", models.CharField(blank=True, max_length=20, null=True)),
                ("statut_payement", models.BooleanField(default=False)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="qr_codes/")),
                ("prix_normal", models.BigIntegerField()),
                ("prix_vip", models.BigIntegerField(blank=True, null=True)),
                ("prix_vvip", models.BigIntegerField(blank=True, null=True)),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=150)),
                ("normal_capacity", models.IntegerField(default=0)),
                ("vip_capacity", models.IntegerField(default=0)),
                ("vvip_capacity", models.IntegerField(default=0)),
                ("image", models.ImageField(blank=True, null=True, upload_to="event_images/")),
                (
                    "type_event",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Privé")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("statut", models.BooleanField(default=True)),
                (
                    "type_access",
                    models.CharField(
                        choices=[("gratuit", "Gratuit"), ("payant", "Payant")],
                        default="payant",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.category"
                    ),
                ),
            ],
        ),
    ]
