# Generated by Django 5.1.1 on 2024-12-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_payement_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="name",
        ),
    ]
