# Generated by Django 5.1.4 on 2025-01-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_contact_alter_event_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catgorie"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Evenement"},
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Partenaire"},
        ),
        migrations.AlterModelOptions(
            name="payement",
            options={"verbose_name": "Payement"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket"},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="prix_normal",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="prix_vip",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="prix_vvip",
        ),
        migrations.AddField(
            model_name="event",
            name="prix_normal",
            field=models.BigIntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="prix_vip",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="prix_vvip",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
