# Generated by Django 5.1.4 on 2025-01-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="prix_vip",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="prix_vvip",
            field=models.BigIntegerField(default=0),
        ),
    ]
