# Generated by Django 5.1.4 on 2025-01-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_alter_event_prix_vip_alter_event_prix_vvip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
