# Generated by Django 5.1.4 on 2025-01-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_alter_event_end_date_alter_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="partner",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="event_partner", to="event.partner"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="prix_normal",
            field=models.BigIntegerField(default=0),
        ),
    ]
