# Generated by Django 5.1.4 on 2025-01-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_alter_event_partner_alter_event_prix_normal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payement",
            name="tickets",
        ),
        migrations.AddField(
            model_name="payement",
            name="mode_payement",
            field=models.CharField(
                choices=[
                    ("orange_money", "Orange money"),
                    ("mobile_money", "Mobile money"),
                    ("paycard", "Paycard"),
                    ("visa", "VISA"),
                ],
                default="orange_money",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="nom_complet",
            field=models.CharField(default="Ibrhahima Diallo", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="payement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ticket_payement",
                to="event.payement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="partner",
            field=models.ManyToManyField(related_name="event_partner", to="event.partner"),
        ),
    ]
