# Generated by Django 5.1.4 on 2025-01-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0012_remove_payement_tickets_payement_mode_payement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payement",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payement_event",
                to="event.event",
            ),
            preserve_default=False,
        ),
    ]
