# Generated by Django 5.1.4 on 2025-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0013_payement_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payement",
            old_name="mode_payement",
            new_name="payment_method",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="email_reception",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="nom_complet",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="statut_payement",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="telephone_payement",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="telephone_reception",
        ),
        migrations.AddField(
            model_name="payement",
            name="email_reception",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="payement",
            name="nom_complet",
            field=models.CharField(default="Diallo", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payement",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="payement",
            name="statut_payement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payement",
            name="telephone_payement",
            field=models.CharField(default=62378327, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payement",
            name="telephone_reception",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="type_ticket",
            field=models.CharField(
                choices=[("normal", "Normal"), ("vip", "VIP"), ("vvip", "VVIP")],
                default="normal",
                max_length=20,
            ),
        ),
    ]
