# Generated by Django 5.1.4 on 2025-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0014_rename_mode_payement_payement_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_img",
            field=models.ImageField(blank=True, null=True, upload_to="ticket_images/"),
        ),
        migrations.AlterField(
            model_name="payement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("orange_money", "Orange money"),
                    ("mobile_money", "Mobile money"),
                    ("paycard", "Paycard"),
                    ("visa", "VISA"),
                ],
                default="orange_money",
                max_length=25,
                null=True,
            ),
        ),
    ]
