# Generated by Django 5.1.4 on 2025-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_ticket_ticket_img_alter_payement_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_img",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_pdf",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
