# Generated by Django 5.1.7 on 2025-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0019_alter_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="partner",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="event_partner", to="event.partner"
            ),
        ),
    ]
