# Generated by Django 5.1.7 on 2025-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0020_alter_event_partner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False, null=True, verbose_name="Lu"),
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=200, null=True, verbose_name="Objet"),
        ),
    ]
