# Generated by Django 5.1.7 on 2025-03-28 01:19

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0021_alter_contact_options_contact_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nom de l'invité")),
                ("email", models.EmailField(max_length=254, verbose_name="Email de l'invité")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message personnalisé"),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("vip", "VIP"), ("vvip", "VVIP")],
                        default="normal",
                        max_length=20,
                        verbose_name="Type de ticket",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("declined", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=100, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="event.event",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation",
                        to="event.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
