# Generated by Django 5.1.7 on 2025-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0022_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
