# Generated by Django 5.1.7 on 2025-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0024_partner_is_platform_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
