# Generated by Django 5.1.7 on 2025-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0025_alter_partner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="is_platform_partner",
            field=models.BooleanField(default=False),
        ),
    ]
