# Generated by Django 5.1.7 on 2025-05-09 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_alter_partner_is_platform_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
