# Generated by Django 5.1.7 on 2025-05-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0028_payement_operation_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payement",
            name="telephone_payement",
        ),
    ]
