# Generated by Django 5.1.7 on 2025-06-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0029_remove_payement_telephone_payement"),
    ]

    operations = [
        migrations.AddField(
            model_name="payement",
            name="quantity_normal",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payement",
            name="quantity_vip",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payement",
            name="quantity_vvip",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
