# Generated by Django 5.1.7 on 2025-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0030_payement_quantity_normal_payement_quantity_vip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="partner",
            field=models.ManyToManyField(
                blank=True, related_name="event_partner", to="event.partner"
            ),
        ),
    ]
