# Generated by Django 5.2.9 on 2026-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0032_add_event_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("lengopay", "Lengo Pay"), ("invitation", "Invitation")],
                default="lengopay",
                max_length=25,
                null=True,
            ),
        ),
    ]
