name: Pipelines CI/CD ProEvent

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  check_syntaxes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Créer le fichier .env
        run: |
          echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env

      - name: Vérifier le fichier .env
        run: cat .env | grep -E '^[A-Z_]+='

      - name: Charger les variables d'environnement
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment variables
        run: env | sort

      - name: Check lint code with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=100

  test:
    runs-on: ubuntu-latest
    needs: check_syntaxes
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgre
          POSTGRES_DB: task_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Charger les variables d'environnement
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Attendre PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "En attente de PostgreSQL..."
            sleep 2
          done

      - name: Appliquer les migrations Django
        run: python manage.py migrate

      - name: Exécuter les tests unitaires
        run: pytest --disable-warnings
